---
title: "BLR_elo"
author: "Hong Duc Vu"
date: "2026-03-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
pacman::p_load(tidyverse, tidymodels, skimr, VGAM, MASS)
```

```{r}
df <- readRDS("./cleaned_data/2026-04-26-atp_matches_best_of_3_ELO.rds")

df <- df %>% 
  mutate(match_outcome = case_when(
    (match_outcome == "WW" | match_outcome == "LWW" | match_outcome == "WLW") ~ "W",
    (match_outcome == "LL" | match_outcome == "WLL" | match_outcome == "LWL") ~ "L"
  )) %>%
  drop_na(match_outcome) %>%
  mutate(match_outcome = factor(match_outcome)) 

w_c <- df %>% filter(match_outcome == "W") %>% count() %>% pull()
l_c <- df %>% filter(match_outcome == "L") %>% count() %>% pull()

print("W count: ")
print( w_c)
print("L count: ")
print(l_c)
```

```{r}
set.seed(42)
df_split <- initial_split(df, prop=0.8)
df_train <- training(df_split)
df_test  <- testing(df_split)

# cross-validation folds
df_folds <- vfold_cv(df_train, strata = match_outcome)

```

```{r}
df_test %>% filter(match_outcome == "W") %>% nrow()
df_test %>% filter(match_outcome == "L") %>% nrow()
```


```{r}

lr_recipe <- 
  recipe(
    match_outcome ~ rank_diff + elo_diff + age_diff + ht_diff + 
      surface + player1_hand + player2_hand,
    data = df_train
  ) %>%
  step_dummy(all_nominal_predictors()) %>%
  # step_zv(all_predictors()) %>%
  # step_lincomb(all_predictors()) %>%
  step_center(rank_diff, elo_diff, age_diff, ht_diff)


train_prep <- lr_recipe %>% prep() %>% bake(new_data = NULL)
test_prep  <- lr_recipe %>% prep() %>% bake(new_data = df_test)

# model
lr_model <- logistic_reg() %>%
  set_mode("classification") %>%
  set_engine("glm")

# workflow
lr_wf <- workflow() %>%
  add_recipe(lr_recipe) %>%
  add_model(lr_model)

# cross-validation 
lr_resamples <- fit_resamples(
  lr_wf,
  resamples = df_folds,
  control = control_resamples(save_pred = TRUE)
)
```




```{r}
lr_resamples %>% collect_metrics()
```


```{r}
# predict on test set
lr_test <- lr_wf %>%
  last_fit(split = df_split) %>% 
  collect_predictions()
```


```{r}
# --- Accuracy ---
acc <- lr_wf %>%
  last_fit(split = df_split) %>% 
  collect_metrics() %>% 
  filter(.metric == "accuracy") %>% pull(.estimate)
acc
```


```{r}
cm <- lr_test %>% conf_mat(estimate = .pred_class, truth = match_outcome)
cm
```


```{r}
# Per-class accuracy
per_class_accuracy <- diag(cm[[1]]) / colSums(cm[[1]])
per_class_accuracy
```

```{r}
lr_test %>% filter(match_outcome == "L") %>% nrow()
lr_test %>% filter(match_outcome == "W") %>% nrow()
```

```{r}
# --- Calibration --- 
# pacman::p_load(caret)
# cal <- calibration(
#   lr_test$match_outcome ~ lr_test$`.pred_W`,
#   data = lr_test)
# 
# plot(cal)


W <- lr_test %>% filter(match_outcome == "W") %>% count() %>% pull()
pi <- sum(lr_test$.pred_W)

calibration <- pi / W

calibration

```


```{r}
# --- Log-loss ---
# N := #matches
N <- lr_test %>% nrow()

# y := actual outcome of set 1
y <- ifelse(lr_test$match_outcome == "W", 1, 0) 
# pi := probability that player with higher rank will win
pi <- lr_test$`.pred_W`
eps <- 1e-15
pi <- pmin(pmax(pi, eps), 1 - eps)


# Log-loss
log_loss <- (-1) / N * sum(y * log(pi) + (1-y)*log(1-pi))
log_loss
```


```{r}
lr_metrics = tibble(
  metric = c("accuracy", "calibration", "log-loss"),
  estimate = c(acc, calibration, log_loss)
)

lr_metrics
```

# P-values of coefficients
```{r}

wf_fit <- lr_wf %>%
  last_fit(split = df_split)

model <- wf_fit$.workflow[[1]] %>%
  extract_fit_parsnip()

temp <- summary(model$fit)$coefficients

tab <- tibble(
  feature = rownames(temp),
  p_value = temp[, grep("Pr", colnames(temp))]
)
tab

tab %>% filter(p_value < 0.05)
```

